# Generated by Django 3.1.3 on 2020-12-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weeb', '0003_auto_20201224_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(help_text='length of comment should be less than 150 characters', max_length=150),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='weeb.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, help_text='length of caption should be less than 100 characters', max_length=100),
        ),
    ]
