# Generated by Django 3.1.3 on 2020-12-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weeb', '0004_auto_20201224_0917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
