# Generated by Django 3.1.4 on 2020-12-25 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weeb', '0008_auto_20201224_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='none', help_text='140 characters or less.', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='fullName',
            field=models.CharField(default='full user name', help_text='60 characters or less.', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='twitterHandle',
            field=models.CharField(default='example', help_text='40 characters or less.', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(help_text='should only contains alphabetic or numeric character.', max_length=30),
        ),
    ]
