# Generated by Django 3.1.4 on 2020-12-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeb', '0017_auto_20201227_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='140 characters or less.', max_length=140),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitterHandle',
            field=models.CharField(blank=True, help_text='40 characters or less.', max_length=40),
        ),
    ]
